package(default_visibility = ["//visibility:public"])

cc_library(
    name = "kernel",
    srcs = glob(
        ["**/*.cc"],
        exclude = ["**/*_test.cc"],
    ),
    hdrs = glob([
        "**/*.h",
        "backend/opencl/*.h",
    ]),
    includes = [".."],
    copts = ["-std=c++20"],
    deps = [
        "@local_cuda//:cuda",
        "@local_cuda//:cuda_runtime",
        "//Omni-Runtime/utils:utils",
    ],
    linkopts = [
        "-ldl",
        "-lOpenCL",
        "-lpthread",
    ],
)

cc_test(
    name = "opencl_jit_test",
    srcs = ["backend/opencl/opencl_jit_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":kernel",
        "@googletest//:gtest_main",
    ],
)
